name: Hourly Feature Pipeline

on:
  schedule:
    # Runs every hour at minute 0 (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:   # Allows manual trigger from GitHub UI

jobs:
  run-feature-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from secrets
        run: |
          echo "OPENWEATHER_KEY=${{ secrets.OPENWEATHER_KEY }}" >> .env
          echo "LAT=${{ secrets.LAT }}" >> .env
          echo "LON=${{ secrets.LON }}" >> .env
          # Add Hopsworks secrets if you use them
          echo "HOPSWORKS_API_KEY=${{ secrets.HOPSWORKS_API_KEY }}" >> .env
          echo "HOPSWORKS_PROJECT=${{ secrets.HOPSWORKS_PROJECT }}" >> .env
          echo "HOPSWORKS_HOST=eu-west.cloud.hopsworks.ai" >> .env
          echo "HOPSWORKS_PORT=443" >> .env

      - name: Run feature pipeline
        run: python src/feature_pipeline.py